### ISSUE TITLE
License

### ISSUE THREAD

**Issue by spiegelball** [compphoto/BoostYourOwnDepth#1]
This is a great project. Is it possible to obtain a commercial license?

**Comment by spiegelball** [comment]
Hey Sebastian, the text of your answer has disappeared the moment I read it.

**Comment by sebastian-dille** [comment]
Hey. Yes, I actually didn't reply here. You should have gotten an email instead.
If that hasn't worked, could you write me a short mail that I can reply to?
You'll find my e-mail here: https://sebastian-dille.github.io/

**Comment by yaksoy** [comment]
Hey. 

If you are an artist who wants to create and sell artwork using our code, please do so! That would make us happy and we'd appreciate a credit to our method and video/repo.

If you want to redistribute our code or application, we do not provide commercial licences at least not yet. Redistribution terms are provided in our repo license, which is only for research purposes.
