### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [compphoto/BoostYourOwnDepth#2]
Thanks for sharing this great work!  

Can you provide some more detailed installation instructions?  For example, a "requirements.txt", or setting up a conda env?  

Also, can you think of an automated way to run this on an image sequence?

**Comment by sebastian-dille** [comment]
Hi,
this repository is an extension to our official paper repo and it's meant mainly as an interactive solution to boost depth maps via the provided colab notebook.

However, our official repo contains all the required information to install the framework locally. You can find it here: https://github.com/compphoto/BoostingMonocularDepth

With the instructions there, it should also be possible to write e.g. a simple batch script for automating the process.

Hope this helps!
Best
Sebastian
