### ISSUE TITLE
Google Collab not working

### ISSUE THREAD

**Issue by oGrqpez** [compphoto/BoostYourOwnDepth#3]
I ran section two, put in the values, and it gave the check mark, but when I run section 3 (I have the low and high res images in their places), it gives an error and no output

**Comment by sebastian-dille** [comment]
Hi, can you please describe the error and the exact values you chose? Maybe we can reproduce it.

**Comment by AW-bass** [comment]
same here

**Comment by sebastian-dille** [comment]
Hi @AW-bass, can you please provide more information about the error?
