### ISSUE TITLE
Low Res and High Res?

### ISSUE THREAD

**Issue by GrandaddyShmax** [compphoto/BoostYourOwnDepth#7]
i may have misunderstood some step..
But where do i produce the low resolution depth map and high resolution depth map?
I've tried your previous colab: https://colab.research.google.com/github/compphoto/BoostingMonocularDepth/blob/main/Boostmonoculardepth.ipynb
But there is no High res or Low res. unless you consider Midas and LeRes to be the high res and low res outputs
I would really appreciate some guidance on how to get the High res and Low res depth map outputs

Thank you in advance!

**Comment by sebastian-dille** [comment]
Hi @ClownOfMadness, 
this notebook is set up to merge any (dense) depth maps that you input.
You could, for example, use the R20 output from our other notebook (in your link) as high-res input. To get the R20 result, just replace the '-Final' option in section 3 with '-R20'. 

Our notebooks do not generate the low-res results, but you can use the original MiDaS/DPT repository to generate them.
Just make sure that the images have the same file name when you merge them.

Hope this helps

**Comment by suptimq** [comment]
I wondered how you generated the high-res depth map using `dpt_beit_large_512`. I think by simply replacing the `-Final` option to `-R20` would raise the error since the model architecture is different.

**Comment by sebastian-dille** [comment]
Hi @suptimq ,
we construct the high-res depth for our method exclusively from ConvNets architectures by utilizing their
specific behavior for our purposes. You can find more info in the main repository and our paper here:
https://github.com/compphoto/BoostingMonocularDepth

Other architectures such as DPT BEiT can still be used to get the base depth map (no R20 in this step). In this case, you could further enhance the depth with details from a ConvNet.

Hope this helps
Sebastian

**Comment by suptimq** [comment]
Hi @sebastian-dille , that makes sense in theory. I guess I am interested in the particular way to generate high-res and low-res using transformer models as the latest MiDas provided.  As mentioned in https://github.com/compphoto/BoostYourOwnDepth/issues/6
