### ISSUE TITLE
TypeError in Section 3

### ISSUE THREAD

**Issue by codestuff001** [compphoto/BoostYourOwnDepth#8]
I'm trying to use the Colab notebook: https://github.com/compphoto/BoostYourOwnDepth/blob/main/colab/byod.ipynb

I have a lowres & hires depth map in the corresponding `/content/BoostYourOwnDepth/input/` folders, both with the same file name, but i'm getting this error when running the cell in Section 3:
```
initialize network with normal
loading the model from /content/BoostYourOwnDepth/pix2pix/checkpoints/mergemodel/latest_net_G.pth
start processing
Traceback (most recent call last):
  File "/content/BoostYourOwnDepth/boost_depth.py", line 146, in <module>
    run(dataset_, option_)
  File "/content/BoostYourOwnDepth/boost_depth.py", line 54, in run
    for image_ind, images in enumerate(dataset):
  File "/content/BoostYourOwnDepth/utils.py", line 194, in __getitem__
    return Depths(self.lr_depth_dir,self.hr_depth_dir, self.files, index)
  File "/content/BoostYourOwnDepth/utils.py", line 174, in __init__
    self.low_res = read_image(os.path.join(lr_dir, name))
  File "/content/BoostYourOwnDepth/utils.py", line 26, in read_image
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)/255.0
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

**Comment by sebastian-dille** [comment]
Hi @codestuff001,
just to make sure: are there any non-image files in the low-res folder when you're running the code?
Those might create the error.
Otherwise, what file type are you using? png and jpg should work fine, but we haven't tested much else.

**Comment by codestuff001** [comment]
When I run the last cell with the preinstalled example depth maps it works, but when I delete the example files and upload my own pngs I get the error. There's one other item in the folders that appears when I delete the example files, it looks like a hidden folder called ".ipynb_checkpoints", other than that there's just the pngs I uploaded:
![230510-211955-chrome](https://github.com/compphoto/BoostYourOwnDepth/assets/111013672/65d9dd65-8c67-4b1c-8f55-c5d35822506f)

Here's a zip with the the input images so you can check the filteypes. I actually produced my depth maps with the Boost Monocular Depth notebook:
https://drive.google.com/file/d/1dv-yx-8p8It7Bhue9v7kZHn3Iqq2EcHk/view?usp=sharing

**Comment by sebastian-dille** [comment]
thanks @codestuff001 
I think the .ipynb_checkpoint-files are creating the issue here.
Our script tries to interpret them as images and then throws the error.
I'll update the script over the weekend. For now, you should be able to get your results when you just delete these files manually.

**Comment by codestuff001** [comment]
Unfortunately I can't delete `.ipynb_checkpoint`, it brings up the folder deletion confirmation dialog, but after clicking "OK" the folder remains:
![230512-172020-chrome](https://github.com/compphoto/BoostYourOwnDepth/assets/111013672/df891301-ed37-4e08-ad66-1ba36cad4135)

Even if I leave the example files in the input folders and simply add my png files, I still get the same "unsupported operand type" error.

**Comment by sebastian-dille** [comment]
hey @codestuff001,
I modified the code so that it ignores hidden files.
Please give it another try, it should work now.
