### ISSUE TITLE
no outputs??  it says finished but no outputs?? 

### ISSUE THREAD

**Issue by nikovladmir** [compphoto/BoostYourOwnDepth#9]
No errors.
Images seem to finish processing practically instantly.
No outputs
Tested on Google Colab GPU and on local CPU

`
PS C:\Users\testiee\Desktop\BOOST\BoostYourOwnDepth-main\BoostYourOwnDepth-main> python3 ./boost_depth.py --data_dir "C:\Users\testiee\Desktop\BOOST\BoostYourOwnDepth-main\BoostYourOwnDepth-main\input" --output_dir "C:\Users\testiee\Desktop\BOOST\BoostYourOwnDepth-main\BoostYourOwnDepth-main\output" --checkpoints_dir ./pix2pix/checkpoints
device: cpu
Namespace(data_dir='C:\\Users\\testiee\\Desktop\\BOOST\\BoostYourOwnDepth-main\\BoostYourOwnDepth-main\\input', output_dir='C:\\Users\\testiee\\Desktop\\BOOST\\BoostYourOwnDepth-main\\BoostYourOwnDepth-main\\output', checkpoints_dir='./pix2pix/checkpoints', output_resolution=1, pix2pixsize=1024, colorize_results=False, max_res=inf)
----------------- Options ---------------
                    Final: False
                       R0: False
                      R20: False
             aspect_ratio: 1.0
               batch_size: 1
          checkpoints_dir: ./pix2pix/checkpoints
         colorize_results: False
                crop_size: 672
                 data_dir: C:\Users\testiee\Desktop\BOOST\BoostYourOwnDepth-main\BoostYourOwnDepth-main\input   [default: None]
                 dataroot: None
             dataset_mode: depthmerge
                 depthNet: None
                direction: AtoB
          display_winsize: 256
                    epoch: latest
                     eval: False
            generatevideo: None
                  gpu_ids: 0
                init_gain: 0.02
                init_type: normal
                 input_nc: 2
                  isTrain: False                                [default: None]
                load_iter: 0                                    [default: 0]
                load_size: 672
         max_dataset_size: 10000
                  max_res: inf
                    model: pix2pix4depth
               n_layers_D: 3
                     name: void
                      ndf: 64
                     netD: basic
                     netG: unet_1024
 net_receptive_field_size: None
                      ngf: 64
               no_dropout: False
                  no_flip: False
                     norm: none
                 num_test: 50
              num_threads: 4
               output_dir: C:\Users\testiee\Desktop\BOOST\BoostYourOwnDepth-main\BoostYourOwnDepth-main\output  [default: None]
                output_nc: 1
        output_resolution: None
                    phase: test
              pix2pixsize: None
               preprocess: resize_and_crop
                savecrops: None
             savewholeest: None
           serial_batches: False
                   suffix:
                  verbose: False
----------------- End -------------------
initialize network with normal
loading the model from ./pix2pix/checkpoints/mergemodel\latest_net_G.pth
start processing
processing image 0 : C:\Users\testiee\Desktop\BOOST\BoostYourOwnDepth-main\BoostYourOwnDepth-main\input\low-res\Lunch_atop_a_Skyscraper

(1543, 2000)
processing image 1 : C:\Users\testiee\Desktop\BOOST\BoostYourOwnDepth-main\BoostYourOwnDepth-main\input\low-res\Lunch_atop_a_Skyscraper_mix

(1543, 2000)
processing image 2 : C:\Users\testiee\Desktop\BOOST\BoostYourOwnDepth-main\BoostYourOwnDepth-main\input\low-res\Motorcycle-perfect

(2000, 2964)
finished
`

**Comment by adam-kosinski** [comment]
@nikovladmir  I was having this issue too. There's a bug in the code when creating the output filepath, the input filename wasn't split from its original path before being joined to the output directory. So the outputs were being stored in the input directory, overwriting the low res inputs. To fix, change line 69 in boost_depth.py to the following:
`path = os.path.join(result_dir, os.path.basename(images.name))`

**Comment by durbar2003** [comment]
did this fix the issue?

**Comment by adam-kosinski** [comment]
> did this fix the issue?

@durbar2003 Yes, the change I suggested fixed the issue for me, if that's what you're asking.

**Comment by JisasPatel** [comment]
do any of you got great results like shown in their paper??
i am getting the depth scan in the output but it's very low quality, not as good as in their paper...
can anyone help me, what is the exact procedure...

**Comment by sebastian-dille** [comment]
Hi @JisasPatel, if you want to reconstruct the results from our paper, it would be easier to use our main repo here: https://github.com/compphoto/BoostingMonocularDepth

This repo is more intended for cases where you already have your own base and detail layer.
